package com.jvjp.calculadora.contants

const val N0 = "0"
const val N1 = "1"
const val N2 = "2"
const val N3 = "3"
const val N4 = "4"
const val N5 = "5"
const val N6 = "6"
const val N7 = "7"
const val N8 = "8"
const val N9 = "9"
const val POINT = "."
const val SIGNAL = "+/-"
const val MINUS = "-"
const val PLUS ="+"
const val DIVIDE = "÷"
const val MULTIPLY = "×"
const val AC = "AC"
const val BACK = "BACK"
const val EQUAL = "="
const val ERROR = "Error"